### ISSUE TITLE
ArduCAM 5MP instead of ArduCAM 2MP

### ISSUE THREAD

**Issue by momu** [maxritter/diy-thermocam#10]
Hi, 
while compiling the BOM for my camera I saw that on watterott the [2MP Arducam][1] is not available but there is a [5MP version][2].
Can you tell if this one will also work without further changes?
Thanks,
Moritz

[1]: http://www.watterott.com/de/2MP-Mini-Kamera-Board-OV2640
[2]: http://www.watterott.com/de/5MP-Mini-Kamera-Board-OV5642

**Comment by maxritter** [comment]
Dear Moritz,

the 5MP version uses a different image sensor (OV5642) than the 2MP version (OV2640).

The OV5642 is currently not supported by the firmware. You may need to adjust this file: https://github.com/maxritter/DIY-Thermocam/blob/master/Firmware/Source/Hardware/Camera/Camera.h

You can get the sources for the OV5642 from here: https://github.com/ArduCAM/Arduino/tree/master/ArduCAM. It's located in Arducam.cpp and the ov5642_regs.h.
