### ISSUE TITLE
DIYLepton_Connect()->Index was outside the bounds of the array

### ISSUE THREAD

**Issue by logicmim** [maxritter/DIY-Thermocam#100]
Hello,  could you explain this error message "DIYLepton_Connect()->Index was outside the bounds of the array".  Is it possible to make an adjustment in Thermovision to fix this.  
Thank you for your comments.

**Comment by maxritter** [comment]
@gallionjason The serial connection is indeed broken with ThermoVision. Please reach out to https://joe-c.de/pages/projekte/thermovision.php for a possible bugfixes. In the meantime, you can use the Thermal Live Viewer that works well with the latest firmware: https://github.com/maxritter/diy-thermocam/tree/master/software/thermal_live_viewer
