### ISSUE TITLE
TP4057 Charging module no longer available

### ISSUE THREAD

**Issue by rossoe** [maxritter/DIY-Thermocam#103]
Hi
I'm searching for TP4057 and I've only seen stock of below item in India with no international shipping available.
![image](https://user-images.githubusercontent.com/28996048/212694171-55bd8acb-35a0-47be-95a9-19535b12354d.png)

This is the only similar part I can find in UK on ebay:
![image](https://user-images.githubusercontent.com/28996048/212694349-9082025a-e8c6-4b69-b5b1-d6ef9da0e769.png)
But it's holes are in different locations so would not match the pins on motherboard.

What is best option? Can above be hacked to fit with wires rather than relying on pins?

**Comment by Gilabite** [comment]
I used a TP4056, no mods to the board needed. these are what I used https://www.amazon.com/gp/product/B00LTQU2RK/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by rossoe** [comment]
Ah yes I just spotted someone mentioning the use of TP4056 here - https://github.com/maxritter/DIY-Thermocam/issues/66
They gave a little detail re the schematic:
![image](https://user-images.githubusercontent.com/28996048/212730155-c394ec4c-4935-40e6-9822-6929796e9c54.png)

I'm fairly new to electronics so just to confirm is this how it should end up - I assume the cables to the rear LIPO holes ensures it makes use of reverse polarity protection on charging board?:
![image](https://user-images.githubusercontent.com/28996048/212733067-67a3ed1e-891e-493f-8dfe-3ae542355485.png)

**Comment by maxritter** [comment]
There is indeed no way to source the TP4057 anymore. Thanks for the instructions how to make it work with the TP4056. I have included this as the default part in the partlist now.

**Comment by rossoe** [comment]
ok a little update as I just finished putting it together and now have what I think is the correct setup, this keeps all the wiring on one side of the pcb, as there was not much room between case and pcb to have wires around the back connecting the lipo battery as per discussions in this [thread](https://github.com/maxritter/diy-thermocam/issues/66).
The wires to the LED also allowed me to get both green and blue working which reflects both 'charging' and 'full' states for battery.
![image](https://github.com/maxritter/diy-thermocam/assets/28996048/3f2f938c-407f-4c24-bd29-4bbddf4dae74)

![image](https://github.com/maxritter/diy-thermocam/assets/28996048/b08adcb0-6a4d-44f3-8031-e5fce1f004cd)

![image](https://github.com/maxritter/diy-thermocam/assets/28996048/c7068113-7cb2-4874-9ec4-b0923c5b251d)

**Comment by maxritter** [comment]
@rossoe Thanks for the detailed update with the images and I am glad it works this way!

**Comment by chrisp429** [comment]
Do you think TC4056 with usb-C would suit? I would prefer to use a usb-C cable instead of mirco USB.
Eg: 
![image](https://github.com/maxritter/diy-thermocam/assets/25708248/db0a7c9e-4606-48dd-8ffe-ff3bcfa9a7a8)
like this one:
https://www.amazon.it/Aideepen-Interfaccia-ingresso-caricabatterie-protezione/dp/B0BZS73V5T/
or
https://www.amazon.it/AZDelivery-%E2%AD%90%E2%AD%90%E2%AD%90%E2%AD%90%E2%AD%90-TP4056-regolatore-carica/dp/B07D2G345P/

**Comment by rossoe** [comment]
I've used that one, however as you can see from the pics above the intended charging slot facing out is the Micro USB on the teensy 4.1 microcontroller which has corresponding hole cut out on the case, so unless you use the whole unit without a case it's not really practical to rotate the charge controller board and make a new hole in the case for it.

**Comment by chrisp429** [comment]
> I've used that one, however as you can see from the pics above the intended charging slot facing out is the Micro USB on the teensy 4.1 microcontroller which has corresponding hole cut out on the case, so unless you use the whole unit without a case it's not really practical to rotate the charge controller board and make a new hole in the case for it.

Thank you rossoe, it is correct, I haven't assembled one yet, so I was confused :).
Chris
