### ISSUE TITLE
Charging and powering over USB

### ISSUE THREAD

**Issue by maitredede** [maxritter/diy-thermocam#2]
Hi,
Can it be possible to change the powering parts to allow the device to work and be charged at the same time, like cell phones ? 
This will remove the need of the power switch.
It can allow to work with external batteries, and let change these external batteries without having to stop operations.

**Comment by maxritter** [comment]
It is possible to operate the device and let it be charged at the same time.
The external power switch is only there to supply other devices with current from the internal battery, like the video output module. So in top position it is charge & operate, and in bottom it is supply power from my internal battery to the USB port.
