### ISSUE TITLE
Lepton 3.5

### ISSUE THREAD

**Issue by Loremwriter** [maxritter/diy-thermocam#23]
Hello,

Just a little question from germany. :)
I want to start to build this project, but im just wondering, if I can order the Lepton 3.5 Sensor instead of the lepton 3.0. 
Is the 3.5 radiometric or do I have to expect any obstacles while building your thermocam with a 3.5 instead of 3.0?

https://www.digikey.de/scripts/DkSearch/dksus.dll?Detail&itemSeq=256344870&uq=636579089465335088

Best regards

**Comment by maxritter** [comment]
The Lepton3.5 is pretty new, it was just released last week.
It is fully radiometric like the Lepton2.5, so you do not need the MLX90614 spot sensor.

I will hopefully get my Lepton3.5 by the end of next week, so I can make the firmware compatible with it. On the hardware side, you don't have to worry about any changes.

Wishes,
Max

**Comment by Loremwriter** [comment]
That's great!
Yes its quite new, but could you maybe post a reply, if it works with Laptop 3.5. 
At this moment I would order my parts to build the cam. Or do you think I can order it anyway, because the firmware will be compatible then? :)

Thanks. :)

**Comment by maxritter** [comment]
You can go ahead and buy it, I will make the firmware compatible next weekend if my sensor is already there until then ;)

**Comment by ulab** [comment]
I was thinking about upgrading my cam to the 3.5 since I broke the shutter when taking apart my One for the sensor. Does it hurt if the spot sensor is soldered in when switching the module?

**Comment by maxritter** [comment]
Nope, the spot sensor is just not used when a radiometric Lepton is detected.

**Comment by maxritter** [comment]
Support for the FLIR Lepton3.5 was added with FW version 2.45

**Comment by Loremwriter** [comment]
Thank you! :)

Just a quick question concerning the Lepton:
Is there a difference between the "500-0771-01-ND" and the "500-0771-01"?
![bildschirmfoto 2018-04-07 um 21 49 41](https://user-images.githubusercontent.com/34414945/38459725-c6bf22bc-3aad-11e8-9290-5415c88f5ac1.png)

And is there any reason why I should buy the resistive LCD instead of the capacitive, like controller or compatibility? I guess I would prefer the capacitive. :)
