### ISSUE TITLE
Wire.endTransmission() and Wire.beginTransmission() should not be used with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [maxritter/diy-thermocam#24]
The Wire.endTransmission() after the Wire.requestFrom() and the Wire.beginTransmission() before the Wire.requestFrom() can be removed in the next files:
- DIY-Thermocam/Firmware/Source/Hardware/Touchscreen/FT6206_Touchscreen.cpp
- DIY-Thermocam/Firmware/Source/Hardware/Lepton.h
- DIY-Thermocam/Firmware/Source/Hardware/MLX90614.h

In "DIY-Thermocam/Firmware/Source/Hardware/Touchscreen/FT6206_Touchscreen.cpp" there is also requesting 32 bytes, but using only 16 bytes.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes) number 2 and 3.

**Comment by maxritter** [comment]
Thanks for the information.
It's worth mentioning, but I haven't noticed any bugs or issues by using the Wire library in the way it's implemented in the firmware at the moment.
That's why I will close this issue until there is a real problem.
