### ISSUE TITLE
Fahrenheit not displaying properly in temp bar

### ISSUE THREAD

**Issue by JSField** [maxritter/diy-thermocam#25]
I have a Lepton 3 with the spot sensor, firmware v2.44, and when I turn on the unit in °F mode, after the warmup, the numbers in the bar are wrong. They go from low negative numbers to extremely high positive numbers. If I change to °C, the numbers are still wrong, until I reboot the camera, then they are ok. If I switch to °F, the bar numbers are OK, unless I try to use Manual, try to adjust the min or max, the + and - buttons change the values by large steps. Something appears to be wrong with °F conversion.

**Comment by JSField** [comment]
Heres what it looks like when in °F mode:

![20180408215115](https://user-images.githubusercontent.com/22135629/38475747-13930228-3b78-11e8-9c6f-d8b2f56def23.gif)

**Comment by maxritter** [comment]
Thanks for the observation.

There was indeed a mistake in the fahrenheit conversion, that caused the mentioned bugs.
It's fixed now and will be implemented in the next FW release.

**Comment by maxritter** [comment]
Should be fixed in FW version 2.46. If not, please reopen this issue.
