### ISSUE TITLE
Updating from FW1.24

### ISSUE THREAD

**Issue by gumbymoegoe** [maxritter/diy-thermocam#27]
![image](https://user-images.githubusercontent.com/38395899/38777015-c98b4758-40f4-11e8-841b-d07c2c83698e.png)

Hi I'm trying to get our cam up to the latest FW but am having issues with the Updater.
When I hit connect the cam says that its connected and turns its screen off but the updater gets stuck on the hardware version detector part.
is there an older version of the updater available so that I could maybe bring it up to speed in stages?

Thanks

**Comment by maxritter** [comment]
You can continue flashing without an activate connection, this will only check battery status and current firmware.
If the DIY-Thermocam Updater does not work, you can also use the Teensy Loader. Hope that helps!

**Comment by gumbymoegoe** [comment]
Hi Max,
Ended up going the Teensy route as the Updater was not completing the flash.( after pressing the flash button a pop up box asking to confirm comes up however after confirmation it still displays awaiting user input below flash button).

anyhow Teensy worked and it is now all updated 
Thanks for the help
