### ISSUE TITLE
Can't update the firmware

### ISSUE THREAD

**Issue by mapperfr** [maxritter/diy-thermocam#31]
Hi,
I finished to build the cam yesterday and I'm trying to make it work, but I can't pass the firmware update step. The cam does not appear as a COM port device, and I think that's why the updater can't see it : 
![capture2](https://user-images.githubusercontent.com/3398608/39294027-e51e3f04-493a-11e8-9cd5-72ddc049af4f.PNG)
I tried to update it on a Mac with teensyduino buyt it doesn't work either.
Any hint?
Thanks!

**Comment by maxritter** [comment]
Please use the new firmware updater 1.20 together with the updated firmware guide.

Those do not require the device to show up as a serial device.

**Comment by mapperfr** [comment]
Thanks for the quick answer!
The new firmware updater just doesn't see the cam, asking me to connect it. Then it says "Waiting for device". Should I try to short the pins P and G as it is indicated in the firmware update guide? And if so, could you please indicate me which pins are P and G?

**Comment by maxritter** [comment]
Yeah, you should short those two pins when the device is connected to the PC and turned on for about a sec. Afterwards, try again to flash the firmware.

Image is here: https://raw.githubusercontent.com/maxritter/DIY-Thermocam/master/Images/Website/TeensyProgram.png
