### ISSUE TITLE
Microcontroller teensey 3.5 is not detected on my pc

### ISSUE THREAD

**Issue by nacerazel** [maxritter/diy-thermocam#32]
Hello everyone, i m already finished the realisation of the thermal camera, the problem that stops me is non detection of teensy, I installed the drivers needed in "device firmware"  but the probleme still exist, no port is detected on arduino ide when i put on my teensy, please i need help

**Comment by maxritter** [comment]
Were you able to flash the device firmware over the official firmware updater or the Teensy loader? Only afterwards, the device will be detected as a virtual serial port on the PC.

**Comment by nacerazel** [comment]
the problem of port 10 is solved, but in "device firmware" remains a driver that always mentions the yellow triangle, I tried to find it with driver finder but the problem always resides, other thing the COM port gives me the com 19 "the 10 is mentioned already used". now I have reached the level of Upload the Hex file in teensy loader but the display still shows nothing "a white screen lit", what can i do please ?

**Comment by nacerazel** [comment]
thank you for your information, now i put it on my camera and it shows me a screen message " this is you first time setup...." they tell me to touch screen but it doesnt respond, a friend tell me that i have to upload source code for the screen but i dont have any idea. 
Thanks

**Comment by maxritter** [comment]
Closed, because the author opened another issue related to the touchscreen.
