### ISSUE TITLE
my touchscreen doesn t respond

### ISSUE THREAD

**Issue by nacerazel** [maxritter/diy-thermocam#34]
I plugged my camera v1 on pc, the screen showed me the initialization images and the message "this is your first use please touch screen" I touch the screen but no answer, do I have to configure the screen?
i need help
Thanks a lot

**Comment by maxritter** [comment]
The screen should work out-of-the box.

Did you order it from here: http://www.buydisplay.com/default/3-2-inch-capacitive-touchscreen-240x320-tft-lcd-module-display using the following configuration: 5V, Pin header 4-wire SPI, resistive touch, no font chip?

Please check all the connections going from the 40-pin display header to the Teensy using a Multimeter, the pinmap (https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/Pinmap_2.1.pdf) and schematic (https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/Schematic_2.3.pdf). You can also have a look at the datasheet of the display module to see which pin has which functionality (p. 11 ongoing): https://github.com/maxritter/DIY-Thermocam/blob/master/Datasheets/DisplayModule.pdf

Hope that helps!
