### ISSUE TITLE
Touchscreen freezes on the booting message

### ISSUE THREAD

**Issue by nacerazel** [maxritter/diy-thermocam#37]
Hello , my touchscreen is freezing on the booting message , it show me to touch screen but it doesn t respond
Best regards

**Comment by Loremwriter** [comment]
Do you have the capacitive or resistive touch panel?

**Comment by Loremwriter** [comment]
BTW: Is there a way to make a capacitive display work into the cam?
It just tells me while booting that the Display initialization failed. :/

**Comment by nacerazel** [comment]
I have resistive touch panel, 
I don t know if there is a way to make a capacitive display . I have the same probleme , after booting it tells me that display is failed

**Comment by maxritter** [comment]
Closed -> Duplicate issue
