### ISSUE TITLE
Lepton 2.5 & 3.0 ambient temperature compensation

### ISSUE THREAD

**Issue by John12341234** [maxritter/diy-thermocam#4]
I'm referring to "ambient temperature compensation" as an automatic correction of the pixel values based on the temperature of the lepton core. I'm not referring to flat-field correction.

1. Does the Lepton 2.5 have ambient temperature compensation enabled by default, without any commands being sent to it?

2. Does the Lepton 3.0 have ambient temperature compensation enabled by default, without any commands being sent to it?

**Comment by maxritter** [comment]
1.: Yes, the Lepton2.5 has integrated ambient temperature compensation, as the radiometry function is enabled by default.
2.: For the Lepton2.0 and Lepton3.0 modules, the ambient temperature sensor of the external spot sensor (MLX90614) is used for compensation.
