### ISSUE TITLE
"Trying to start..." on boot menu

### ISSUE THREAD

**Issue by Loremwriter** [maxritter/diy-thermocam#40]
Hi,

i ordered a new display, which is resistive instead of capacitive. At first, everything was fine. I got to a menu to set up the time and date, but then after restart my camera get stuck on the boot menu. 
Here is the current screen. Every time I start up, it get stuck at this screen. 
![2018-06-01 15 57 45](https://user-images.githubusercontent.com/34414945/40844917-756c46a0-65b5-11e8-9a75-a17729a2d903.jpg)

Does anyone has an idea, how to fix it?

I already flashed a new firmware to the camera (Version 2.46 from 17.04.2018).

Best regards

**Comment by maxritter** [comment]
There seems to be an issue with the I2C bus, because all devices using it are shown as "Failed". So maybe there is a short somewhere or the 4.7k pullup resistors are not connected properly. Resoldering the affected connections also helps sometimes :)
