### ISSUE TITLE
Practice Image Set

### ISSUE THREAD

**Issue by gabynordic** [maxritter/diy-thermocam#41]
I am waiting on all of my parts to arrive, but want to start developing in the meantime. Does anyone have raw data and temperature files taken on this camera that they would be willing to share?

Thanks!

**Comment by maxritter** [comment]
You can use the SAMPLE.DAT file from here:
https://github.com/maxritter/DIY-Thermocam/tree/master/Software/Thermal%20Analysis%20Software

The raw data files structure is described here:
https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/RawData_07.pdf

Am Di., 10. Juli 2018 um 22:05 Uhr schrieb gabynordic <
notifications@github.com>:
