### ISSUE TITLE
The camera is stuck with a screen that says "Please wait. ." whenever I try to access either cam

### ISSUE THREAD

**Issue by billgrava** [maxritter/diy-thermocam#42]
Each time I attempt to access either the thermal or visual camera, I get stuck with a white screen that says "Please wait. ." that does not change no matter how much time I give it. The self-diagnostic does not detect any errors with the cameras, so I am wondering if there is anything I should check for or if there is a reboot procedure I need to do. Thank you.

**Comment by maxritter** [comment]
Have you been able to use the cam normally before?
When you flash the EEPROM_Clear script from here: https://www.dropbox.com/s/jqcwolz5vajj0u5/eeprom_clear.ino.hex?dl=1
And afterwards the newest firmware again, are you able to see the thermal and/or visual image during the first start procedure?

**Comment by billgrava** [comment]
I flashed the EEPROM_Clear and then the new firmware again, but it did not seem to fix the problem. I have not been able to use the cam before. Initially when I was building the camera I put the IR sensor in the wrong way. I eventually took it out all together and have not put the IR Sensor back in. I understand that the thermal camera will not work but was hoping that the regular visual camera would.

**Comment by himike12** [comment]
Were you able to resolve this problem? I am having the same issue with mine.

**Comment by maxritter** [comment]
Are you using a non-radiometric Lepton with the MLX90614 spot sensor, or a radiometric without?

You should use a multimeter with the connection checker, and go through the important connection using https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/Schematic_2.3.pdf and https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/Pinmap_2.1.pdf. 

The components that can cause a freeze in this screen are the visual camera, the Lepton and optionally the spot sensor. So check correct power supply and data connection lines (SPI & I2C) for those.

**Comment by himike12** [comment]
Thank you maxritter for getting back to me. 
I am using the radiometric Lepton without the spot sensor. I will confirm the connections.

**Comment by HateFindingNames** [comment]
Same here. Lepton 2.5, no MLX installed, ArduCam 2MP plus version, newest firmware. All Supply and data connections already checked.
It stays at the self diagnostic screen (everything ok except the spot sensor) forever giving me the message "trying to start..." unless I touch the screen.
Inside the menu is everything but everytime I try to get an image from visual or thermal it is just telling me to wait without anything happening ever. Touching the screen to get back into the menu works. Only the calibration screen makes the whole device freeze while it is stuck at 0%.

Do you have any suggestions?

**Comment by maxritter** [comment]
@HateFindingNames Unfortunately, the issue is very hard for me to reproduce here. I have the unverified assumption that the radiometric version of the Lepton is not recognized correctly, so the device tries to connect to the non-existing MLX90614 spot sensor.

What you can try to verify this is install the SDK IDE by following the steps here: https://github.com/maxritter/diythermocam_firmware/

Then in lepton_init() under /src/hardware/lepton.cpp, print out whats the content of the variable leptonVersion after lepton_version() has been called (Serial.println(leptonVersion)). It should be 3 if the Lepton2.5 is recognized correctly.

**Comment by HateFindingNames** [comment]
Thanks for the quick reply. I am at work right now but Iwill let you know as soon as I'm back.

@maxritter so, Lepton version gives me 0. Bad news I guess? 0o

**Comment by HateFindingNames** [comment]
Ok, after some further investigation it turned out that in fact this lepton seems to be a non-radiometric version. Doh!
Is there a way to make use of it - for now - without haveing a MLXP attached?

@billgrava I guess by now it is not relevant anymore but I think you ran into the same situation...

**Comment by maxritter** [comment]
Makes sense then. Unfortunately, if you use a non-radiometric Lepton, the DIY-Thermocam needs the MLX90614 attached to be working correctly.

**Comment by HateFindingNames** [comment]
Ok, I'm going to order one and reply as soon as I know more.

It is easier for me to order at mouser. They got the MLX with the part-no 482-90614ESFBCF000SP.
On the picture it is missing the optics tube but the part description/specs are all the same compared to digikey. Do you happen to have any experience with the mouser part? Is it safe to order?

**Comment by maxritter** [comment]
The part number is right, so I think they just used the wrong picture. Should be good to go :)

**Comment by HateFindingNames** [comment]
Good news - MLX is the right one. More good news - it's working ;) thank you very much. I think you can consider this issue solved.

**Comment by maxritter** [comment]
Perfect! I am glad it is working now :)
