### ISSUE TITLE
Silkscreen mirrored in gerber file

### ISSUE THREAD

**Issue by Nprod** [maxritter/diy-thermocam#51]
Hi there, i'm preparing to have a few PCBs made of the latest version (2.3) and the silkscreen text for the major components like the camera, lepton breakout etc. is mirrored in the gerber preview. Is this normal? Both the viewer at http://www.gerber-viewer.com/ and the one at http://jlcpcb.com shows reversed text for the bottom layer while the top layer is fine.

**Comment by maxritter** [comment]
Looks pretty normal to me:

![silkscreen](https://user-images.githubusercontent.com/12452009/48442804-81dec500-e78f-11e8-8959-98d4d962d466.JPG)

Also when I manufactured them, I didn't notice any mirrored silkscreen..

**Comment by Nprod** [comment]
This is how it looks in JLCPCB's viewer, comparing it to your picture it looks like the entire board is mirrored on the bottom view.
![mirrored](https://user-images.githubusercontent.com/10956716/48481608-e3964200-e816-11e8-98d4-ebaf3729d33d.png)

I guess it's a quirk of the website, i wanted to make sure it's correct since it's not the only online gerber viewer that showed it like this.
