### ISSUE TITLE
No USB Icon in the menu 2.47

### ISSUE THREAD

**Issue by Vital1984** [maxritter/diy-thermocam#52]
Hello

I finished v2 yesterday

I have flashed the latest firmware 2.47

but I have no USB icon in the menu to transfer the files to the pc.

I would be glad about help

**Comment by maxritter** [comment]
Hey there,

only the DIY-Thermocam V1 has USB mass storage support. For the V2, you have to eject the SD card and put it into a card reader on your PC. Therefore the icons is not showed in the menu.
