### ISSUE TITLE
Problems FIRST firmware installation

### ISSUE THREAD

**Issue by LenzoM** [maxritter/diy-thermocam#53]
Hello,

I can't install the firmware for the fist time in the camera. I have just assembled it all and so I want to flash the firmware.

With the updater from the software folder, and the last HEX files from the firware section. I connect the camera to the computer ( I have installed the DRIVE.exe) and I get these messages.

How do you see them?

![image](https://user-images.githubusercontent.com/35913662/50525438-c6be8100-0adb-11e9-8c5b-66c2facf7758.png)

![image](https://user-images.githubusercontent.com/35913662/50525456-da69e780-0adb-11e9-8b5f-d43204023e6c.png)

![image](https://user-images.githubusercontent.com/35913662/50525468-e2298c00-0adb-11e9-837c-da92c864020b.png)

**Comment by LenzoM** [comment]
Someone help¿

**Comment by maxritter** [comment]
Sorry for the late reply!

Please use the Teensy Loader from here: https://github.com/maxritter/DIY-Thermocam/tree/master/Software/Firmware%20Updater/Teensy%20Loader

Open Teensy.exe, load the V2 hex file, connect the Thermocam to the PC and turn it on. Then launch Teensy_Reboot.exe, the flash procedure should start now.

**Comment by LenzoM** [comment]
Hello Max!

Thank you for your reply :)

I, after some troubles, finally managed to connect the camera to de computer and finally I could reboot the hex file, until i get the message, from the teenesy program of OK. But, after that, my screen gets frozen in this picture and it doesn't seem likely to move on.

![photo_2019-03-07_20-21-37](https://user-images.githubusercontent.com/35913662/53983281-2ad27680-4117-11e9-8043-7a5a0c254186.jpg)

I wish you could help me!

**Comment by stephen94000** [comment]
Hello, I'm currently facing the same problem as you do. Have you managed to bypass this screen ?

**Comment by stephen94000** [comment]
I think this is somehow related to the hardware detection of the components in the device?

**Comment by maxritter** [comment]
Dear @LenzoM , dear @stephen94000 ,

sorry for my late reply, I was on vacation. Stephen is right, this is most likely related to one or some of the hardware components not working / not connected properly. 

Please use a multimeter and check all the connection to the sensors (SPI & I2C Lepton, I2C MLX90614 for non-radiometric, SPI & I2C camera). You could use those two documents for that purpose: https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/Pinmap_2.1.pdf & https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/Schematic_2.3.pdf. Also check if the supply voltage for all components is correct and the Lipo is fully charged.

If the problem still persists, you could install the Eclipse IDE, load the firmware project there and insert Serial Outprints at different stages of the startup procedure. This way you can identify where the procedure hangs up. Setting up the IDE is described here: https://github.com/maxritter/diythermocam_firmware

Let me know if this helps :) 

Best,
Max

**Comment by Meins321** [comment]
Well i had the same problem i did build a V2 with new 2MP ArduinoCam and it wont boot on 2.48!

Just check 2.46 or 2.45 from the old firmware repository:
http://diy-thermocam.bplaced.net/Firmware/
Or 2.47 from here:
https://github.com/maxritter/diythermocam_firmware/releases

Multimeter error research time:
It shows the traces from one spot to another
[PCB 2.3.pdf](https://github.com/maxritter/DIY-Thermocam/files/3156544/PCB.2.3.pdf)
Maybe this helps and you can add it to the repository for people without eagle!

**Comment by LenzoM** [comment]
Thank you for your kind help! It works now fine!! 
I have another issue, but i open now another topic
