### ISSUE TITLE
Combined view / camera issue

### ISSUE THREAD

**Issue by cvbkf** [maxritter/diy-thermocam#56]
hello, 
i got my thermocam from the latest groupget round #15 with a lepton 3.5. now, i am pretty sure that i did the assembly right - but the thermal and the visual image are way off regarding the field of view and can't be combined. 

these photos are taken with a tripod, with at least one meter distance to the target. 

![20180914062644](https://user-images.githubusercontent.com/16870924/51548621-feb1ad80-1e68-11e9-88c3-fe12ba77d182.JPG)
![20180914062644_th](https://user-images.githubusercontent.com/16870924/51548622-feb1ad80-1e68-11e9-8062-2c096c22a7f1.jpg)

i don't think the visual image is right, and i can't adjust the images properly in the menu. is there something wrong ? 

on a side note: how long does saving an image usually take ?

**Comment by maxritter** [comment]
Dear @cvbkf , 

what exactly do you mean you can't adjust the combined image in the menu? Are the buttons not working? There is a small parallaxe between the visual and thermal sensor, and they also do not have the exact same field of view.

Thats why for different distances to the scene / target, it's required to adjust them manually. In your scenario, go to Combined Mode and enter the Adjust Combined menu. Create a new setting, then press the "-" button a couple of times to make the visual image smaller. Afterwards, use the direction arrows to move both images above each other and save the settings. It should be used in the combined mode and for taking visual images afterwards.

Saving a combined image or saving an image with the convert to BMP option enabled takes much longer than saving a raw thermal image only (<1), up to 5 seconds.

Best,
Max
