### ISSUE TITLE
Documentation changes for ThermalLiveViewer

### ISSUE THREAD

**Issue by Nprod** [maxritter/diy-thermocam#59]
The current documentation for the Thermal Live Viewer on how to run the program on Linux is confusing and mixed with misleading instructions for OSX (something about Jason's iPhone?). The source for the program seems to also have changed since the documentation was written. Here is my revision of how the instructions should read:

> If the comport is not COM10 on Windows, you need to change it. 
>On Linux, look for changes in the list of devices in /dev/ - the camera will be listed as a terminal device in the manner of "ttyACM0". You can also list them in the terminal with the "ls /dev/tty*" command.
>Edit the "ThermalViewer.py" file, find the line that reads "device = "COM10" under the "Global Variables" section and change it to the full path of the device, for example:
>
>device = "/dev/ttyACM0"
>
> And save the file.

>If there are problems getting the UI to show up, run the program in terminal (e.g. "python ./ThermalViewer.py"). If there are missing dependencies, they will be listed. The program depends on packages like pygame,pybutton and scipy - if they are missing, you can install them using the command "pip install", for example "pyp install pygame".

I'm not an OSX user so i can't say what the instructions should be there. I imagine the prodecure is somewhat similar.

**Comment by maxritter** [comment]
Thanks for the feedback! I replaced your suggestions with the old content.
