### ISSUE TITLE
assembly instructions feedback

### ISSUE THREAD

**Issue by nielsswinkels** [maxritter/diy-thermocam#6]
First off, I'm impressed by the great documentation so far! I thought I would give my feedback on the building instructions after just having gone through assembling one camera. None of these were dramatic, as I managed to put it together, but it might be nice to know about.

1. I missed some parts in my kit:
  - the male 40 pin header that should have been on the display module.
  - the pieces of wire and heatshrink
2. the 40 pin female header had a little piece of plastic sticking out on on of the long sides, which i had to file off to make it fit
3. In step 3 "remove the overlapping pieces with a gripper" took me a moment to be sure what you meant. I would write something like "Cut the pins short with cutting pliers, right above the solder points you just made"
4. In step 5 I was surprised with having to break pieces off haha 😄 
5. In step 6 I had to look very close to figure out that the black spacers were not all the same size. If someone tries to go fast they will probably do this wrong. Also the 3mm spacer in the bottom right corner didn't want to stay put in that place,it kept falling out.
6. In step 7 I first thought you wanted me to remove the plastic piece on the front of the thermal camera. Maybe you should write more clearly that it is the plastic from the angled male pins that should be removed?
7. in step 8 I actually soldered the angled female header after having put everything together. Also I don't get why you wanted 2 of the spacers to not be on the top 2 bolts. Don't they fit there maybe?
8. In step 10, maybe you can write something about how to identify which version of the FLIR lepton sensor you have?
9. In step 11 I first soldered the led in all the way like you write, but then I couldn't bend it 90 degrees, so had to re-do that one. 
10. In which step should you actually place the battery? It is never written (or I missed it)
11. In step 12 I mounted the tripod mount pointing outwards. It was only once I was done that I saw a picture somewhere else of how it should have been. Could you add a photo in this step?
12. In step 19, maybe you can describe which way the right panel should be in. It is hard to see that it actually makes a difference which way is up.

Anyway, do far I'm really impressed, and really looking forward to using it!

**Comment by maxritter** [comment]
Dear Niels,

thank you very much for your detailed feedback!

I updated the assembly guide to revision 5 including your recommended changes.
Sorry about the missing parts in your kit. The kits are sourced and packaged by GroupGets, I do not have any influence on this. But I forwarded the information to them, so it hopefully does not happen again in the future.

Wishes,
Max
