### ISSUE TITLE
How to order the board?

### ISSUE THREAD

**Issue by Thanh-Binh** [maxritter/diy-thermocam#64]
Hi,
could you please inform me how to order the board or complette system?
Best thanks

**Comment by WoodsideOak** [comment]
When I built the camera, I had to order 10 printed circuit boards.  They are for the V2 Thermocam, Rev 2.3 boards.

I only used one board and will sell the others at cost (1GBP each) plus postage.

![IMG_20190405_114517](https://user-images.githubusercontent.com/11885779/55622589-86d0ff00-5798-11e9-9481-16d7411e261e.jpg)
![IMG_20190405_114000](https://user-images.githubusercontent.com/11885779/55622450-26da5880-5798-11e9-8408-88e6a68d4cd1.jpg)

**Comment by KrisJot** [comment]
Hi,

I'm new on github.

@WoodsideOak what copper thickness did You choose, 1oz,? I'm interested with ordering one from You.

**Comment by WoodsideOak** [comment]
@KrisJot Yes 1oz copper.  Board spec as follows:
    - Material: FR-4 TG130
    - Layer: 2
    - Dimension (Length): 89
    - Dimension (Width): 68
    - Solder Mask Color: Green
    - PCB Thickness (mm): 1.6
    - Copper Thickness: 1 oz
    - Surface Finish: HASL (Hot Air Solder Leveling)
    - Min. Tracking / Spacing: 6 mil
    - Min. Hole Size: 0.3 mm
    - Fiducial Mark: Yes
    - Polishing Technique: Polishing

**Comment by KrisJot** [comment]
@WoodsideOak, thats great, would like to buy two pcb from You.

**Comment by WoodsideOak** [comment]
@KrisJot No problem.
The boards cost me 1GBP each so I will sell for that price. 
Please send me a private message with your address and I will calculate postage to you.

**Comment by FuwoWolf** [comment]
Hi @WoodsideOak , are there still boards left?

**Comment by WoodsideOak** [comment]
@FuwoWolf, yes I have boards left.

I've sent you a PM with postage costs.

**Comment by hasulhas** [comment]
Hi @WoodsideOak , i want to buy them all

**Comment by WoodsideOak** [comment]
@hasulhas - No problem, i have 8 boards left and will sell them at £1 each.
Please email me your address and I will calculate the postage.

**Comment by turbopropello** [comment]
Would love one of them too

**Comment by jonaswinterhalder** [comment]
@WoodsideOak Would like to buy one too. I will write you.

**Comment by WoodsideOak** [comment]
I now have 6 boards left

**Comment by jbiz111** [comment]
Hi, id like to buy 2 or 3 if still available.

**Comment by Fischgeburt** [comment]
Has anyone 1-2 PCBs which aren't needed anymore?

@WoodsideOak Maybe?

**Comment by WoodsideOak** [comment]
> 
> 
> Has anyone 1-2 PCBs which aren't needed anymore?
> 
> @WoodsideOak Maybe?

Yes, I have 5 boards left and will sell them at £1 each.
Please email me your address and I will calculate the postage.

**Comment by Fischgeburt** [comment]
@WoodsideOak 

Sent you an email.

**Comment by User35123** [comment]
@WoodsideOak 

is still one available? I would like to get one.
Thank you!

**Comment by WoodsideOak** [comment]
Hi,

 

Yes, I have two boards left.  I will sell them at cost price of 1GBP each, plus postage.

 

If you send me your address I will let you know what the postage would be.

 

Regards

Malcolm
