### ISSUE TITLE
Cam does not boot in battery mode

### ISSUE THREAD

**Issue by DavidWid** [maxritter/diy-thermocam#65]
Hi,

I completed my Thermocam build and I'm running into a weird problem right now.
When booting the camera when it's connected to a usb power suply, everything works fine.
But when I'm starting the cam without external power suply, the screen lights up I can hear (and see) the thermal sensor shutter closing and reopening, but the boot screen does not appear and the camera does not boot.
I'm by no means an electrical engineer, so I'm afraid I might have wired something wrong regarding the battery (thoug I'm quit sure I followed the instructions here).
Is there any way to toubleshoot whats wrong with my camera?

**Comment by stephen94000** [comment]
Hey, I had the same trouble, However, by rewiring everything, it worked. Check if your battery is fully charged, Have you welded everything on a PCB or are you using a bread board ?
