### ISSUE TITLE
Replacement for TP4057 charging module

### ISSUE THREAD

**Issue by KrisJot** [maxritter/diy-thermocam#66]
Hi,
 
can be used TP4056 as replacement for TP4057 from part list?

**Comment by maxritter** [comment]
It does not exactly fit the holes on the PCB, but from the charging perspective, it should work. However, you need to solder cables to the LEDs on the module and remove them, if you want to use the charging light functionality.

**Comment by KrisJot** [comment]
Thank you for reply. Will try and let you know about the result.

**Comment by Meins321** [comment]
> 
> 
> It does not exactly fit the holes on the PCB, but from the charging perspective, it should work. However, you need to solder cables to the LEDs on the module and remove them, if you want to use the charging light functionality.

Maybe it is the better option?

I did buy the TP4057 off ebay with blue pcb, but i got the green pcb and it doesnt work. My lipo did not charge and the whole board just heated up like warm toast.
the teensy is dead now :-(

The lepton still works as i tested it with another socket

So don't use the green TP4057 which is delivered from ebay from many sellers

**Comment by Meins321** [comment]
@maxritter : Maybe a word of warning towards those who buy blue pcb on ebay and get green one with mixed -/+ on battery terminals?

Something like this _should_ work:
![PCB Charger TP4056 Mod](https://user-images.githubusercontent.com/47847723/57378238-97640300-71a4-11e9-86d1-a9075cf8679f.jpg)

You can use the included protection too! i would also route a cable to the back into the Lipo connector to get it to the intended place...

The original board looked like this:
![TP4057 1A](https://user-images.githubusercontent.com/47847723/57378631-7a7bff80-71a5-11e9-8104-3d2ad0ab2ff2.jpg)
What i got looked similar but DO NOT USE IT:
![s-l300](https://user-images.githubusercontent.com/47847723/57379800-e3fd0d80-71a7-11e9-8882-6c5cffa9a549.jpg)


The green pcb one didn't work, i bought two of them and i am not using the second one!
It just heated up while the red led was lit, and it didn't charge at all :-1:  

I have to see how much damage the TP4057 caused on my board as many component are not 5V tolerant..teensy i am looking at you!

-40€ down the drain

TP4056 is much better working and i will do this mod too, just a red led on two wire glued in the hole done.

**Comment by KrisJot** [comment]
Hi, TP4056 is charging properly (blue PCB). Lipo charged to 4.2V.

**Comment by rossoe** [comment]
@Meins321 & @KrisJot 
Is this the appropriate wiring for the TP4056 ?
![image](https://user-images.githubusercontent.com/28996048/214288608-ca8fc9e4-c4e5-4b72-95a4-008ac622928c.png)

**Comment by rossoe** [comment]
@maxritter so just to confirm before I solder together and fry anything I shouldn't!
why should we not connect it up like the below?
I'm not sure why @Meins321 recommended the output of the **TP4056** go back to the lipo connector?
![image](https://github.com/maxritter/diy-thermocam/assets/28996048/1a504da6-e11b-4cbf-98ce-175c0997a4e0)

**Comment by rossoe** [comment]
See updates on this [post](https://github.com/maxritter/diy-thermocam/issues/103) for final tested wiring solution including wiring for LED branching off from the led's onboard the newer **TP4056**.
