### ISSUE TITLE
Adding some text over the thermal imaging 

### ISSUE THREAD

**Issue by stephen94000** [maxritter/diy-thermocam#67]
Hello,

I wanted to add a GPS to the Raspberry Pi Zero where the thermocam is connected. 
First, i wanted to try to add some text over the thermal imaging, but i failed... the screen.blit(mytext) just before screen.blit(thermalimage) is not taken in consideration... Have you guys have any clue ? Thanks 
Stephen

**Comment by maxritter** [comment]
In function displayThermalImage after "if thermalImg is None: return", you could add your text this way:

```
font = pygame.font.SysFont("Times New Roman", 26)
mystr = "GPS Text"
color = getTextColor()
text = font.render(mystr, 1, color)
textpos = text.get_rect()
textpos.centerx = thermalImg.get_rect().centerx
textpos.centery = thermalImg.get_rect().centery + 65
thermalImg.blit(text, textpos)
```
