### ISSUE TITLE
Video Output Module - Image leads to 404

### ISSUE THREAD

**Issue by Loremwriter** [maxritter/diy-thermocam#74]
See headline. 
Cant download the firmware image for the module.

Where can i download the image to flash it onto the raspberry pi zero? 

The Link for the complied Thermal Live Viewer is down as well... :( 
The joe-C Version Fails with „LeptonConnect{} - Der Index war außerhalb des Arraybereiches“

**Comment by Gerrit28282** [comment]
Same here

**Comment by Gerrit28282** [comment]
I partly solved the issue. You can find the firmware here: 
https://github.com/maxritter/DIY-Thermocam/tree/master/Software/Video%20Module/2.02 
Just follow the readme an power on the pi.

For me the script does not autostart, I have to manually start it from the console via: "python2 __init__.py"

Depending where that file is located on your SD Card you first have to navigate to that place. For me it is: cd /boot.

Note that the python script is written for python 2.7, some functions like map() and chr(CMD_FRAME_DISPLAY) dont work as supposed under python 3. 

Nevertheless, the issue with the thermal live viewer still exists.

**Comment by Loremwriter** [comment]
Hi Gerrit, 
i just have to copy the "__init__.py" and "config.txt" onto the SD card?
Its the only content, that i can find in the 2.02 zip file. 

So i dont have a boot directory or something like that. 
Or do i have to flash a raspbian version to the sd card?

Thanks in advance! :)

Concerning the thermal live viewer: Im currently in contact with the developer of the app. We are working on a solution to solve the Lepton_Connect Error.

**Comment by Gerrit28282** [comment]
You should have installed a recent Raspbian distribution on your SD card. Easiest way to do that is with the [NOOBS](https://www.raspberrypi.org/downloads/noobs/) installer. 

After that you should find a boot partition on your SD card where you can put both the config and the "__init__.py" file. The init file is basically the firmware which you can manipulate to fit your own needs. 

Would be great if you could share your solutions regarding the live viewer if it works. 

Cheers, 
Gerrit

**Comment by Loremwriter** [comment]
Great, it works! :)

I will share the solution if it works. Probably it takes some more time and will end in an updated version by joe-c.

**Comment by ncbelov** [comment]
Hello! I managed to defeat the autostart of the _init_.py file?
