### ISSUE TITLE
Reupload pls thermal live viewer Compiled version

### ISSUE THREAD

**Issue by Vital1984** [maxritter/diy-thermocam#77]
hey max can you pls reupload compiled version for Windows 10 . the link for download dont work anymore . and i have some Trouble to compile it self 

Edit : now i started  with python but after the text say DIY CAM detected . the app close 
with this messsage : ZeroDivisionError: float division by zero

Edit 2: App is working but say Put the Divece in Live mode . i dont no how ?. screen on Camera go off, 

or the device detect and say me update your device 2.35 or greater  an the app turn off.
my Devise is on the latest firmware 2.48

**Comment by maxritter** [comment]
Here you go: https://www.dropbox.com/s/otar27qetzpolfv/ThermalLiveViewer_2.03.zip?dl=1
