### ISSUE TITLE
video feed

### ISSUE THREAD

**Issue by jackattack21** [maxritter/diy-thermocam#85]
has anyone come up with a way to pipe a thermal sensor into a vlc type feed? can this setup be repurposed for that? If you output the analog video signal and use a analog to digital IP converter for the feed maybe?

**Comment by maxritter** [comment]
@jackattack21 Doing it over the Video Output Module and an IP converter would be possible, although it's not an elegant solution. You may check out the PureThermal 2 from GroupGets (https://groupgets.com/manufacturers/getlab/products/purethermal-2-flir-lepton-smart-i-o-module), it has VLC support.
