### ISSUE TITLE
Arducam 2mp mini plus ov2640

### ISSUE THREAD

**Issue by ncbelov** [maxritter/diy-thermocam#86]
Need help! There is no image from the camera arducam 2mp plus-rev-A working camera checked on arduino uno. What needs to be changed in firmware 2.48 to make it work?
![IMG_20210119_140119](https://user-images.githubusercontent.com/77629193/105718425-a66f8380-5f3a-11eb-9a44-66e677ba3680.jpg)
![IMG_20210121_125617](https://user-images.githubusercontent.com/77629193/105718443-ab343780-5f3a-11eb-9106-d5ea43a0eb89.jpg)

**Comment by maxritter** [comment]
Hey @ncbelov,

sorry for the long waiting time. There have been repeated reports about issues with a newer hardware version of the Arducam and the DIY-Thermocam. I just ordered a new Arducam by myself and will let you know once I have a fix available.

Best,
Max

**Comment by ncbelov** [comment]
Thank

**Comment by ncbelov** [comment]
The camera does not work on firmware 2.48 writes please wait. I am waiting for the updated firmware.

**Comment by boriskogan81** [comment]
Same issue with the same component. I am also not sure how to assemble this physically, since the instructions deal with the previous version (UC-354)-am nervous about breaking it. Please advise.
