### ISSUE TITLE
Camera not working 

### ISSUE THREAD

**Issue by gregg26** [maxritter/diy-thermocam#87]
We used the flip lepton 2 and the firmware doesn’t appear to work. Please help!

**Comment by maxritter** [comment]
Hey @gregg26,

can you please provide additional information about what is not working? Do you see any error on the screen?

As long as the MLX90614 spot sensor is connected, the Thermocam should work with the Lepton2.0

**Comment by gregg26** [comment]
Hey Max thanks for getting back to me. 

Once the camera was assembled Leo never gotten it to power on. We press and hold the power button and it sounds like it’s starting up. The screen flashes on for a second and then it turns off.
