### ISSUE TITLE
thermo and image not match correctly

### ISSUE THREAD

**Issue by LenzoM** [maxritter/diy-thermocam#88]
Dear team,

Now after some problems I finally got the thermoCam. 
But as you can see, it seems that the image is moved from the thermal image.
Not only moved but as well a little farther.

Any tips or suggestion how to improve this error?

![error](https://user-images.githubusercontent.com/35913662/109165764-398b1b80-777c-11eb-8e72-302cbd4118bf.jpg)

Many thanks!!

**Comment by maxritter** [comment]
Dear @LenzoM,

there is a small parallax between Lepton and Visual camera that can't be avoided, as it depends on the distance to the target.

Please check out the [manual](https://github.com/maxritter/DIY-Thermocam/blob/master/Documents/Manual_13.pdf), on the device you can enter the "Adjust combined" menu and calibrate both sensors towards each other. If the matching is still bad, you have to reopen the case and put bigger plastic spacers under the visual camera (as described in the assembly guide).

Hope this helps!
