### ISSUE TITLE
Cam hangs on Boot Screen, Hardware Issue?

### ISSUE THREAD

**Issue by Catarallus** [maxritter/diy-thermocam#89]
Hello together,

my Thermocam won't boot, what I see is the Boot Screen. I guess it's is a hardware problem.

I use the PCB Rev 2.3 with the new Lepton Breakboard V2.0 (20 Pins) and the Lepton 3.5. I also noticed that the Diode on the Lepton Breakoutboard is in the wrong direction. I wired the Voltage source to J3 connector to solve this Problem.
The Arducam is from robotshop which look's like a litte bit different like in the assembly guide, but the pin assignment is the same. In the new BOM is no Arducam listed, is this part obsolet?
I have no MLX90614 installed because in don't need it, right?

The voltage on the Lepton Breakboard and the Arducam is about 5V.

Any suggestions what else I can do to fix the Problem?

**Comment by maxritter** [comment]
Hey @Catarallus!

For the Lepton Breakout Board V2, you need the PCB 3.0 and the firmware version 3.0.
Then the Lepton3.5 will work out-of-the-box and you do not need the MLX90614. 

Unfortunately the visual camera is not supported any more on V3, as it made some problems. But you can always use a regular camera and create combined images on the PC with the ThermoVision software.

Best,
Max

**Comment by Catarallus** [comment]
Hi @maxritter,

tank you for your fast reply.
Flashing Pre Compiled V3 failed with the Teensy Uploader. It seems the file can't be loaded, "unreadable" is shown in the Uploader Statusbar.

greetings
Johannes

**Comment by maxritter** [comment]
Hey @Catarallus,

do you use the Teensy 4.1 and the firmware loader from [here](https://github.com/maxritter/DIY-Thermocam/tree/master/Software/Firmware%20Updater)? Then it should work, just tried it out myself.

Best,
Max

**Comment by Catarallus** [comment]
Hi @maxritter,

yes I use Teensy 4.1. The flash process is now succesfully, but it only works with the push button (it is not easy to push the button if the Teensy is soldered to the PCB already) But who cares.
After Power up the screen is black, now. 
I use farther PCB Rev 2.3. The Lepton is contacted with some wires on the PCB, of course I payed attention to the correct Pins. (The Thermocam will be mounted on a drone, so it's not a Problem). 
What are differents beetwen PCB Rev 2.3 and PCB 3.0? Do I really need the new PCB?

**Comment by Primergi** [comment]
Hi! Are you sure Breakout Board V2 works? You need to remove the Thermocam, and measure the DC-DC voltage.Must be Vcc 1.2v, Vcc 2.8v(if FFC is active), Vcc 3.0v.

**Comment by Catarallus** [comment]
Hi,

I here a "click" noise from the Lepton, it sounds like a camera shutter.
Which measurement points I have to check?

greetings
Johannes

**Comment by Primergi** [comment]
"Which measurement points I have to check?"
Photo of the Breakout Board on the back side please.

**Comment by Catarallus** [comment]
![IMG_20210507_130133](https://user-images.githubusercontent.com/83033653/117441027-1d9eb580-af35-11eb-9588-0d855516dcd9.jpg)

![IMG_20210507_130102](https://user-images.githubusercontent.com/83033653/117441050-23949680-af35-11eb-90cd-bb6219d46e58.jpg)

**Comment by Primergi** [comment]
![Lepton power](https://user-images.githubusercontent.com/83535576/117462344-3e780280-af57-11eb-8522-8948a62d9a29.jpg)

**Comment by Primergi** [comment]
Sorry if something is unclear. I am Russian, and I use a translator :)

**Comment by Jandroks** [comment]
From what you wrote it appears that you connected Teensy 4.1 to the PCB top and therefore nothing can work for you. I put together Thermocam v3. and it worked without any problems.

**Comment by Catarallus** [comment]
@Jandroks 
thanks for your comment.
The pinout between Teensy 4.1 & 3.6 seems the same. Do you also know my combination is not working?

**Comment by Catarallus** [comment]
@Primergi 
> Sorry if something is unclear. I am Russian, and I use a translator .

I understand your suggestion. I will do the measurement if I had time to go ahead with this project.
