### ISSUE TITLE
DiyThermocam V2 Touch lcd

### ISSUE THREAD

**Issue by Primergi** [maxritter/diy-thermocam#90]
Hi. Diythermocam V2. 0 can work with the screen where is the capacitive sensor installed? Or just resistive? Thanks.

**Comment by maxritter** [comment]
Currently the firmware only supports the resistive version of the screen. 
But as it is open-source, feel free to add the missing drivers on your own :)

**Comment by Primergi** [comment]
Thank you for your feedback. Unfortunately I can't find the full description on the screen. I will study the material.
