### ISSUE TITLE
Image transmission via wifi

### ISSUE THREAD

**Issue by Janusz-Janiec** [maxritter/diy-thermocam#92]
hi Max
I put together a Diy-Thermocam according to your design and it works fine. Have you ever wondered whether to use diy-thermocam to send an image via wifi. It would be an interesting option that would make the camera more attractive and find a new crowd of enthusiasts for your venture. I am asking because I am playing with the construction of drones and I thought that it would be worth using the camera to transmit the image in this way. There is a project that uses a version 2 camera and a Raspberry PI designed by you to transmit the image. What do you think.

**Comment by maxritter** [comment]
@Janusz-Janiec Glad to hear the assembly worked and the Thermocam is alive!

Thanks for the suggestion. I am already thinking about a DIY-Thermodrone that has a much more compact form factor and can be attached to a drone for image transmission over WIFI, HDMI or analog video. Unfortunately I am not having much time right now for this as I want to focus on the delivery of the V3 and the extension of the software ecosystem there first, but be assured it's in the back of my mind ;)

**Comment by Janusz-Janiec** [comment]
Thank you for your response.   Good luck in this and your future endeavors.  
            
          
     
      
       
        Dnia 16 maja 2021 18:28 Max Ritter ***@***.***&gt; napisał(a):
       
    
       
         
 github.com @Janusz-Janiec  Glad to hear the assembly worked and the Thermocam is alive! 
 Thanks for the suggestion. I am already thinking about a DIY-Thermodrone that has a much more compact form factor and can be attached to a drone for image transmission over WIFI, HDMI or analog video. Unfortunately I am not having much time right now for this as I want to focus on the delivery of the V3 and the extension of the software ecosystem there first, but be assured it&#39;s in the back of my mind ;)
