### ISSUE TITLE
finished my Themocam, a few remarks for the Enclosure

### ISSUE THREAD

**Issue by helmarw** [maxritter/diy-thermocam#93]
got my display finally :)
every thing is working fine !

![IMG_7059](https://user-images.githubusercontent.com/10408121/118272965-a5e80200-b4c3-11eb-9df6-4f243bfab683.jpg)

i decided to 3D-print the enclosure first before i order a laser cut (if any)
good thing i did, since then i noticed few misalignments.

1) the opening for the USB-Port is to high
![IMG_7057](https://user-images.githubusercontent.com/10408121/118273134-dcbe1800-b4c3-11eb-858f-8d2da44aea70.jpg)

i also used a different t-Nut, because i could not get the one you suggested. only some minor modification nessesary.

2) the hole for the LED has to be 1-2mm more to the center or you need to leave the wires longer
![IMG_7058](https://user-images.githubusercontent.com/10408121/118273367-1ee75980-b4c4-11eb-9ebf-777141fb7091.jpg)

3) most important, the hole for the Lepton is a bit low, i saw the upper edge of the housing in the thermal image
so i cut it a bit higher
![IMG_7056](https://user-images.githubusercontent.com/10408121/118273475-46d6bd00-b4c4-11eb-91f6-6fe479ffa899.jpg)

4) i really didnt like the round head philips screws, so i used black A2 countersunk torx-screws. I think it gives it a nicer finish

**Comment by helmarw** [comment]
i forked your project and added my modifications to my fork. Also added BOMs to all parts i bought
Feel free to use it, if you find it useful...

due to minimum order amount I also have 2 PCBs, 2 Lipo Chargers and a couple of T-nuts left over
if anyone is interested please drop me a line

**Comment by maxritter** [comment]
@helmarw Great to hear it's working now!

The 3D printed enclosure looks great and thanks for the mentioned improvements. I have widened the Lepton cutout a bit to the top as you have suggested, and also slightly extended the microUSB port. Concerning the Charging LED, I am wondering if you have soldered it on the "right" side of the PCB. Maybe this was a bit clear in the first version of the assembly guide, I have updated the guide today with fresh images: https://www.diy-thermocam.net/build-your-own

**Comment by helmarw** [comment]
hi, thnx for the reply
i checked again, i soldered the LED on the correct side of the pcb (other wise it would not hit the hole at all).
in the picture it looked like it needed to be as close as possible to the PCB, but in fact it needs a distance of 1-2mm.
so its better to mount  two or three sides of the housing to the PCB (on the display side) and then try inserting the LED
with 90deg bent leads. once its fits in the hole you can solder it.
in my case the leads are very short, almost flush with the PCB, thats how i interpreted your pictures. A higher res side view of the LED would have be helpful here, to see that the LED needs a bit space to the PCB
Now the LED sits at a aprox. 30deg angle inside the hole. its still working but, so i leave it as it is.

**Comment by helmarw** [comment]
i updated my housing again: https://github.com/helmarw/DIY-Thermocam/tree/master/Images
i put all the stl und dxf files in my fork too

USB-Port fits nicely now
![Bottom](https://user-images.githubusercontent.com/10408121/118656172-9120ac80-b7ea-11eb-9eb2-7a6d4739278e.jpg)

LED a bit better now, not perfect but close enough
![Top](https://user-images.githubusercontent.com/10408121/118656220-9ed63200-b7ea-11eb-9683-b7e7d55a8ac6.jpg)

front with an 8mm hole
![Front](https://user-images.githubusercontent.com/10408121/118656277-ab5a8a80-b7ea-11eb-83cb-e79e65b260ad.jpg)

and added a webcam-cover as lens protection :)  [simple 8mm one from Amazon](https://www.amazon.de/dp/B081J8D756/ref=cm_sw_em_r_mt_dp_3EE2QM3QVHKHH0B3Y5TW?_encoding=UTF8&psc=1)
![Front_with_Lenscover](https://user-images.githubusercontent.com/10408121/118656304-b2819880-b7ea-11eb-9f83-297ed9089c39.jpg)

**Comment by IAowSwels** [comment]
Did you already covered these improvements in the latest CAD files?
