### ISSUE TITLE
Having issues getting the firmware on Teensy

### ISSUE THREAD

**Issue by salsa33** [maxritter/diy-thermocam#94]
When I try to load the firmware on the teensy board through teensy.exe it says the hex file is too large. Verbose info says “file contains data beyond chip size.” I inherited this task of assembling the thermocam from someone else, so I’m unsure if the purchased pieces separately or the kit online. Any info would be appreciated!

**Comment by salsa33** [comment]
Tried getting the firmware onto the Teensy by using VSCode, but now I'm getting errors with MTP even after unzipping the updated info to the correct folder.

**Comment by maxritter** [comment]
Hey @salsa33,

did you assemble the DIY-Thermocam V2 or V3? 

Try to flash this hex file first: https://github.com/maxritter/DIY-Thermocam/blob/4b86ec988f69ddeae3e1c9218e800dde4bc6906f/Software/Firmware%20Updater/Teensy%20Loader/FileTooBig.hex, then try again the compiled firmware version. Make sure that if you have a V2 device, only flash firmware version starting with 2.x. 

Hope that helps!

**Comment by salsa33** [comment]
The board has V3 printed on it. I'm not the one who built the kit, I just inherited the issue XD. I'll try this hex file and see what happens. I'll be working on it later today anyways. Thanks for the response!

**Comment by salsa33** [comment]
Works now, I didn't even need the other hex file, this time when I opened teensy.exe it loaded just fine. Either way, thanks for responding.
