### ISSUE TITLE
Can't find charging module

### ISSUE THREAD

**Issue by Catarallus** [maxritter/DIY-Thermocam#97]
Hello everybody,

i can't find the Charging Module for Thermocam V3. 
Can you tell me the right designation? 

Thanks a lot

**Comment by helmarw** [comment]
if i remember correctly i bought this one:
https://de.aliexpress.com/item/32574075391.html

**Comment by Catarallus** [comment]
It seems  it is the right one.
Thank you

**Comment by JensGrabner** [comment]
Is these the Modul? Google "KitsGuru 5V 1A DUAL TP4057 LITHIUM BATTERY CHARGING BOARD"
