### ISSUE TITLE
Lepton sensor diagnostic failed

### ISSUE THREAD

**Issue by GautierR** [maxritter/DIY-Thermocam#98]
Hi,

Just finished the assembly of my camera. Unfortunately I have a Self-Diagnostic failed for the FLIR Sensor while booting. Is there a way to get a more descriptive issue ? I have double check all the soldering point of the FLIR board. I am using teh latest Firmware 3.02.

I was thinking that it may be due to the sensor not being push enough, but I clearly hear a click. You have bellow some pictures. I got my sensor on Mouser. 

Any advices ? Thanks a lot

![IMG_20220303_190312](https://user-images.githubusercontent.com/19713679/156625973-41c220a4-6852-4263-8705-dc2e389a8542.jpg)

![IMG_20220303_190351](https://user-images.githubusercontent.com/19713679/156626043-94c77cdb-d99e-4fc7-85ec-e580cea51ee9.jpg)

![IMG_20220303_190403](https://user-images.githubusercontent.com/19713679/156626063-ca7eda9d-deab-4db1-91e0-5af0e1f039e4.jpg)

**Comment by helmarw** [comment]
Do you know if the sensor is working at all? Did you test it e.g. on a raspberry first with standard code from flir?
just asking because my first Lepton i got from digikey was broken from the start. after some discussion with flir customer support and digikey i got a refund (not really a 5cent device, so it makes sense to give it some effort :) ). 
second one i bought from mouser and everything work fine from the start ...
I dont think you can do much wrong with this DIY Thermocam, i built it myself and using it ever since ...

**Comment by GautierR** [comment]
I tried to build the code for the raspberrypi_video (see here : [LeptonModule/software/raspberrypi_video](https://github.com/groupgets/LeptonModule/tree/master/software/raspberrypi_video) ) without success.

I am using a raspbian dist, and not able to install qt4-dev-tools (needed for qmake). 

Anyway, I have ordered a new sensor to see if it can works just by switching them.

**Comment by GautierR** [comment]
I have actually managed to get it compiled with qt5 and run the software.

It seems to works even if it's very slow and the refresh is not fast at all.

![image](https://user-images.githubusercontent.com/19713679/156820593-88af95dc-baff-4d59-baee-f0c10bb3615f.png)

I have plugged all back to the DIY-Thermocam PCB, and still get the same issue during the boot

EDIT:

I tried to installed a previous firmware version. The V3.0 gives more info on the possible Lepton failure. It seems that the issue comes from the I2C as shown in #40. Using a multimeter I have checked all the connection from the lepton module to the teensy, all seems okay.

**Comment by GautierR** [comment]
I bought a new sensor, solved the issue.

BTW, I have also designed an updated version of the 3D printed enclosure (thinner and more smooth). I will try to make another iteration to fix some issues and upload both STEP and STL if someone wants it.

![image](https://user-images.githubusercontent.com/19713679/170720687-ad132b92-aa50-47ba-8a84-7715dbbef25a.png)

**Comment by zhaocundang** [comment]
IIC OK , SPI OK, but touch continue lcd show "lepton error , try to reset.." I don't  know where is wrong , how to deal with it
